// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPrnY9uthfdJaG3ViK0EJq70Z1-2_2qQ',
    appId: '1:487441192986:web:b24536a55bfac8de7399a3',
    messagingSenderId: '487441192986',
    projectId: 'ecommerce-app-f0f95',
    authDomain: 'ecommerce-app-f0f95.firebaseapp.com',
    storageBucket: 'ecommerce-app-f0f95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMkLRq01Aa7S-GQMQHTqvrORhaOMB42s',
    appId: '1:487441192986:android:29bfa45b62423b177399a3',
    messagingSenderId: '487441192986',
    projectId: 'ecommerce-app-f0f95',
    storageBucket: 'ecommerce-app-f0f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURFQuDx0_K4OKmU1Klmj7TeVoDVrhYP4',
    appId: '1:487441192986:ios:4ecf223c7961a4287399a3',
    messagingSenderId: '487441192986',
    projectId: 'ecommerce-app-f0f95',
    storageBucket: 'ecommerce-app-f0f95.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURFQuDx0_K4OKmU1Klmj7TeVoDVrhYP4',
    appId: '1:487441192986:ios:4ecf223c7961a4287399a3',
    messagingSenderId: '487441192986',
    projectId: 'ecommerce-app-f0f95',
    storageBucket: 'ecommerce-app-f0f95.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPrnY9uthfdJaG3ViK0EJq70Z1-2_2qQ',
    appId: '1:487441192986:web:9a8f94e37c60022c7399a3',
    messagingSenderId: '487441192986',
    projectId: 'ecommerce-app-f0f95',
    authDomain: 'ecommerce-app-f0f95.firebaseapp.com',
    storageBucket: 'ecommerce-app-f0f95.firebasestorage.app',
  );
}
